### ISSUE TITLE
Contrast for comments is too low

### ISSUE THREAD

**Issue by ajpaulson** [notpratheek/vim-luna#5]
Comment highlighting in almost every filetype is much too low - this can even be seen in the screenshots on your readme.

Maybe just a couple of shades lighter would work?

**Comment by notpratheek** [comment]
@ajpaulson 

This issue was was brought up a couple of times, But the thing is that I prefer comments to hide away from the code, but it seems, they are similar to dark background. 

Anyway, I have made them lighter, here's the changes: 

Prev 

![prev](https://f.cloud.github.com/assets/1803997/1272838/2258f5c2-2d38-11e3-9e91-dbde50c27be9.png)

After

![after](https://f.cloud.github.com/assets/1803997/1272840/2e48acec-2d38-11e3-87fa-2e9530afbeaa.png)

---

I hope these are OK ? :smile:

**Comment by ajpaulson** [comment]
That's great - Thank you very much

**Comment by notpratheek** [comment]
happy to help ! :smile:
