### ISSUE TITLE
Luna color scheme transparent?

### ISSUE THREAD

**Issue by justinpage** [notpratheek/vim-luna#6]
Hello,
Love your color scheme!
Ubuntu 13.10 seems to be having trouble with vim-luna however.
I followed the instructions but still get a transparent background and not the desired effect:
![screenshot from 2013-12-06 01 26 15](https://f.cloud.github.com/assets/3615935/1691030/402f4acc-5e59-11e3-82e8-47bf21291292.png)

I will also attach a link to my .vimrc to make sure it isn't my fault that this is occurring
https://github.com/KLVTZ/dotfiles/blob/master/vimrc

**Comment by notpratheek** [comment]
@KLVTZ  

Thanks for liking the scheme ! :smile: 

I believe its a silly error, in the `.vimrc` you must set colorscheme to **luna-term**, rather than just **_luna**_

I ended up making two separate colorschemes (one with **only** gui values and the other with **only** cterm values), for this reason, 

![has_gui](https://f.cloud.github.com/assets/1803997/1694613/9ab4e222-5ea4-11e3-9b39-3da67831276f.png)

---

So, in your [.vimrc](https://github.com/KLVTZ/dotfiles/blob/master/vimrc#L30), just make the change from 

``` viml
colorscheme luna
```

to 

``` viml
colorscheme luna-term
```

This ensures that, vim (terminal one) has luna-term colorscheme.

---

Hope that helps ! 
Feel free to let me know if you run into any other problems with the colorscheme. :smile:

**Comment by justinpage** [comment]
Thanks for the quick reply! That did fix the transparent background problem but now, I don't think I'm getting the correct colors on my vim. I seem to have a weird color scheme that doesn't match the desired colors from airline on the picture i first posted. Also, the background seems to be a harsh black and not the deep dark grey that is in your example. I'll attach a photo for reference -thank you so much again for all your help
![2](https://f.cloud.github.com/assets/3615935/1695765/d35057a2-5eb7-11e3-93b0-b1dacb6da6bf.png)

**Comment by notpratheek** [comment]
@KLVTZ 

I saw your vimrc, you've enabled 256 colors support in vim :+1:,
but the terminal might not be supporting it 256 colors (:-1:).

To check if your terminal supports 256 colors, Try these: 

First, type this into your terminal : 

``` sh
tput colors
```

This should print out: `256` 

Another test is: 

``` sh
echo $TERM
```

this should output: `xterm-256color`

[If you don't get output as mentioned, or get something different, follow [this](http://whiletruecode.tumblr.com/post/13358288098/enabling-256-color-mode-in-ubuntus-bash-terminal) tutorial to make it right]

## 

Another thing is that, I saw your updated [.vimrc](https://github.com/KLVTZ/dotfiles/blob/925815a09d12e1a77950576a758ed2e5210fa1e5/vimrc#L29), you've set the colorscheme to koehler, which is probably why your getting that harsh black rather that deep dark gray. 

simply set it as `colorscheme luna-term` and it should work !

---

Hope that helps !
Feel free to let me know if you run into any other problems. :smile:

**Comment by justinpage** [comment]
Thanks! I did set out to follow the tutorial and now my system is displaying correctly 256 colors on my bash.I changed my colorscheme back to luna-term as well -my dotfile backup was the kolor theme which has been working fine on my system.

Here's proof of my 256 color support:
![256](https://f.cloud.github.com/assets/3615935/1700054/d8cd2ff4-5feb-11e3-91a9-f38e43e39042.png)

Basing off the logic of 256 color terminal support. It appears that the Normal variable doesn't have a background set. In fact, most of the normal highlighting does not have a background set.
by setting ctermbg in either luna or luna-term:

``` Shell
hi Normal    ctermfg=254 ctermbg=235 cterm=NONE
```

I was able to obtain a dark grey background. Another big difference is that vim airline displays correct colors in your luna.vim file but not your luna-term.vim despite 256 support.

Many color schemes online appear to have combined their ctermbg and guibg variable together into one file. Could doing the same fix not only this solution, but also allow your file to be more universal?

**Comment by notpratheek** [comment]
@KLVTZ 

> It appears that the Normal variable doesn't have a background set. In fact, most of the normal highlighting does not have a background set.

Thanks for that ! I have now updated the terminal to use a proper background for `Normal`
You can check out this commit : d0fcbf4918adda6510b6896d5a60ab32f761be9f

> Another big difference is that vim airline displays correct colors in your luna.vim file but not your luna-term.vim despite 256 support.

When I first created this theme, I made it for gui version of vim. So, I ended choosing imaginative colors :stuck_out_tongue_winking_eye:, and when I had to port it to terminal vim, I tried to match them as close as possible, to the luna.vim. 

You see the variation due to fact that each of the 256 colors have a specific #rrggbb values, so, the 256 colors for airline in luna-term.vim are close (plus or minus) to their #rrggbb values in the luna.vim file. So, they are not **_exact**_ to my imagined colors. 

Here's the difference : 

![term_by_gui](https://f.cloud.github.com/assets/1803997/1706789/df119df6-60f3-11e3-8d02-2bcc55da5e87.png)

(terminal vim on top, and gui vim in the back)

> Many color schemes online appear to have combined their ctermbg and guibg variable together into one file. Could doing the same fix not only this solution, but also allow your file to be more universal?

The cterm values and gui values are **independent** of each other, so in essence, the values have to be set separately for both, terminal and gui. Universal, not really. I'm not sure how many people do this, but I like to have different colorschemes for gui version and terminal version, which has this advantage 

![img](https://f.cloud.github.com/assets/1803997/1694613/9ab4e222-5ea4-11e3-9b39-3da67831276f.png)

If both the values (cterm and gui) are in one .vim file, then it would not be possible to have different colorschemes for terminal and gui. 

---

With respect to your second comment in this thread,

> I seem to have a weird color scheme that doesn't match the desired colors from airline on the picture i first posted.

Simply add `let g:airline_theme = 'luna'` in your `.vimrc`. This ensures that airline uses the luna as its theme. 

## 

Hope that helps ! :smile:

**Comment by justinpage** [comment]
Dude! Thank you so much for all your help and making the changes! It's freaking awesome now! I want to also thank you for all the time you have taken for this and making improvements to a damn good color scheme
![final](https://f.cloud.github.com/assets/3615935/1709694/01be455a-6123-11e3-82d0-1dda4148111f.png)

-happy coding && again, thank you!
